apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h0wueum8v-java-springboot
  janus-idp.io/tekton: h0wueum8v-java-springboot
  backstage.io/kubernetes-id: h0wueum8v-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h0wueum8v-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
